[2024-06-15T21:55:22.734+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-15T21:55:22.753+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_sales_python_dag.copy_to_gcs_task manual__2022-08-09T18:07:09+00:00 [queued]>
[2024-06-15T21:55:22.762+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_sales_python_dag.copy_to_gcs_task manual__2022-08-09T18:07:09+00:00 [queued]>
[2024-06-15T21:55:22.763+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-15T21:55:22.781+0000] {taskinstance.py:2330} INFO - Executing <Task(LocalFilesystemToGCSOperator): copy_to_gcs_task> on 2022-08-09 18:07:09+00:00
[2024-06-15T21:55:22.787+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=73) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-15T21:55:22.789+0000] {standard_task_runner.py:63} INFO - Started process 75 to run task
[2024-06-15T21:55:22.789+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'process_sales_python_dag', 'copy_to_gcs_task', 'manual__2022-08-09T18:07:09+00:00', '--job-id', '331', '--raw', '--subdir', 'DAGS_FOLDER/gcp_sales_load.py', '--cfg-path', '/tmp/tmpij316qk8']
[2024-06-15T21:55:22.792+0000] {standard_task_runner.py:91} INFO - Job 331: Subtask copy_to_gcs_task
[2024-06-15T21:55:22.840+0000] {task_command.py:426} INFO - Running <TaskInstance: process_sales_python_dag.copy_to_gcs_task manual__2022-08-09T18:07:09+00:00 [running]> on host 37ab05bbda86
[2024-06-15T21:55:22.938+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_sales_python_dag' AIRFLOW_CTX_TASK_ID='copy_to_gcs_task' AIRFLOW_CTX_EXECUTION_DATE='2022-08-09T18:07:09+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2022-08-09T18:07:09+00:00'
[2024-06-15T21:55:22.940+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-15T21:55:22.949+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-06-15T21:55:22.950+0000] {base.py:84} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-06-15T21:55:22.951+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-15T21:55:22.952+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/google/cloud/transfers/local_to_gcs.py", line 98, in execute
    raise FileNotFoundError(self.src)
FileNotFoundError: /mnt/file_storage/stg/sales/2022-08-09
[2024-06-15T21:55:22.961+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=process_sales_python_dag, task_id=copy_to_gcs_task, run_id=manual__2022-08-09T18:07:09+00:00, execution_date=20220809T180709, start_date=20240615T215522, end_date=20240615T215522
[2024-06-15T21:55:22.975+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 331 for task copy_to_gcs_task (/mnt/file_storage/stg/sales/2022-08-09; 75)
[2024-06-15T21:55:23.002+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-15T21:55:23.021+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-15T21:55:23.024+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
